---
- hosts: all
  become: yes
  tasks:
    - name: Disable SELinux
      selinux: state=disabled

    - name: Activate network interface eth1
      shell: |
        if [[ -f '/etc/sysconfig/network-scripts/ifcfg-eth1' && "$(grep -i -c '^BOOTPROTO=static' /etc/sysconfig/network-scripts/ifcfg-eth1)" -eq 0 ]]; then
          sudo sed -i -e 's|BOOTPROTO=none|BOOTPROTO=static|' /etc/sysconfig/network-scripts/ifcfg-eth1 && sudo systemctl restart network
        fi

    - name: Install additional packages
      yum: name="{{ item }}" state=present
      with_items:
        - erlang
        - libselinux-python
        - python2-pika
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel

    - name: Install rabbitmq server
      yum: name=https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_11/rabbitmq-server-3.6.11-1.el7.noarch.rpm state=present

    - name: Allow any user connect to rabbitmq server
      copy:
        src: files/conf/rabbitmq.config
        dest: /etc/rabbitmq/rabbitmq.config

    - name: enable rabbitmq server
      service: name=rabbitmq-server enabled=yes state=started

    - name: Create directory for application
      file:
        path: /opt/myapp
        state: directory
        mode: 0755
        owner: vagrant
        group: vagrant

    - name: Copy all needed files for publisher.java app
      copy:
        src: files/publisher/
        dest: /opt/myapp

    - name: Compile java app
      shell: cd /opt/myapp && /usr/bin/javac -cp amqp-client-4.0.2.jar:slf4j-api-1.7.21.jar:slf4j-simple-1.7.22.jar /opt/myapp/Send.java

    - name: Install zabbix repo
      yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present

    - name: Install zabbix packeges
      yum: name="{{ item }}" state=present
      with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
        - mariadb
        - mariadb-server
        - httpd

    - name: Enable and run mysql service
      service: name=mariadb enabled=yes state=started

    - name: mysql_secure_installation
      shell: |
        mysql -e "UPDATE mysql.user SET Password = PASSWORD('zabbix') WHERE User = 'root'"
        mysql -e "DROP USER ''@'localhost'"
        mysql -e "DROP USER ''@'$(hostname)'"
        mysql -e "DROP DATABASE test"
        mysql -e "FLUSH PRIVILEGES"
      ignore_errors: yes

    - name: Configure zabbix server and enviroment
      shell: |
        echo "create database zabbix character set utf8 collate utf8_bin;" | mysql -uroot -pzabbix
        echo "grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbix';"| mysql -uroot -pzabbix
        zcat /usr/share/doc/zabbix-server-mysql-3.0.10/create.sql.gz | mysql -uroot -pzabbix zabbix
        if [[ -f '/etc/zabbix/zabbix_server.conf' && "$(grep -c '^DBPassword=zabbix$' /etc/zabbix/zabbix_server.conf)" -eq 0 ]]; then
          sudo sed -i -e 's|# DBPassword=|DBPassword=zabbix|' /etc/zabbix/zabbix_server.conf && sudo systemctl restart zabbix-server
        fi
        if [[ -f '/etc/php.ini' && "$(grep -c '^date.timezone' /etc/php.ini)" -eq 0 ]]; then
          sudo sed -i -e 's|;date.timezone =|date.timezone = Europe/Moscow|' /etc/php.ini && sudo systemctl restart httpd
        fi

    - name: Copy zabbix web conf
      copy:
        src: files/conf/zabbix.conf.php
        dest: /etc/zabbix/web/zabbix.conf.php
        mode: 0644
        owner: apache
        group: apache

    - name: Start httpd service
      service: name=httpd enabled=yes state=restarted

    - name: Start zabbix server
      service: name=zabbix-server enabled=yes state=restarted

    - name: Start zabbix agent
      service: name=zabbix-agent enabled=yes state=restarted

    - name: Enabled Zabbix host configuration
      shell: echo "update hosts set status = 0 where host like 'Zabbix server';" | mysql -uroot -pzabbix zabbix

    - name: Add zabbix user to sudo to run rabbitmqctl
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^zabbix'
        line: 'zabbix  ALL=(ALL)       NOPASSWD: /usr/sbin/rabbitmqctl list_queues'
        validate: 'visudo -cf %s'

    - name: Add worker host to zabbix configuration
      local_action:
        module: zabbix_host
        server_url: http://localhost/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: worker
        host_groups:
          -   Linux servers
        link_templates:
          - Template OS Linux
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 10.0.0.11
            dns: ""
            port: 10050

